resources:
  - ../../base

images:
  - name: bankapp-image
    newName: thuyein97/bankapp
    newTag: latest


patches:
  - target:
      kind: Ingress
      name: bankapp-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: test.alphareds.com
  - target:
      kind: Deployment
      name: bankapp
    patch: |-
      - op: replace
        path: /metadata/name
        value: prdbankapp
