resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - pdb.yaml

secretGenerator:
  - name: bankapp-secrets
    envs:
      - secret.env
generatorOptions:
  disableNameSuffixHash: true
