resources:
  - ../../base

images:
  - name: bankapp-image
    newName: thuyein97/bankapp
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: bankapp-ingress
    patch: |-
      - op: replace
        path: /metadata/name
        value: stgbankapp-ingress
      - op: replace
        path: /spec/rules/0/host
        value: test2.alphareds.com
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: stgbankapp-service
  - target:
      kind: Service
      name: bankapp-service
    patch: |-
      - op: replace
        path: /metadata/name
        value: stgbankapp-service
  - target:
      kind: Deployment
      name: bankapp
    patch: |-
      - op: replace
        path: /metadata/name
        value: stgbankapp